
@url = "http://localhost:5000"

GET http://localhost:5000/


###
POST http://localhost:5000/start-game
Content-Type: application/json

{
    "username": "nerdraven",
    "mainCode": "1234"
}

###
POST http://localhost:5000/play-move
Content-Type: application/json

{
    "playerId": "nerdraven",    
    "gameId": "1",
    "testCode": "1234",
}